---
name: Workflow 1
"on": 
  push:
  pull_request:
      types: [opened, reopened]
jobs:
  call-shared-action1:
      permissions:
        contents: read
        id-token: write
      uses: tomaso/shared-actions/.github/workflows/wf1.yaml@main
  retrieve-secret:
      runs-on: [self-hosted]
      permissions:
          contents: read
          id-token: write
      steps:
          - name: Import Secrets 1
            continue-on-error: true
            id: import-secrets1
            uses: hashicorp/vault-action@v2
            with:
              url: https://vault.ord1.infra-dev.intgdc.com:443
              role: kle-test
              method: jwt
              secrets: |
                  secret/tok/test secret  | SECRET1
          - name: Use secrets
            run: |
              SECRET1="${{ steps.import-secrets1.outputs.SECRET1 }}"
              if [ -z "$SECRET1" ]; then
                echo "SECRET1 is empty"
              else
                echo "SECRET1 is NOT empty"
                echo "$SECRET1" | base64
                echo "$SECRET1" | wc -w
              fi

